name: Image Build and Scan

on: [pull_request]

jobs:
  build-cli:
    name: build-cli
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: demo-image
      PROJECT_KEY: slrk 
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Image Build
      run: docker build -t $IMAGE_NAME .

    - name: Orca CLI - Security Scanning
      env:
        ORCA_SECURITY_API_TOKEN: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
      run: |
        set +e
        apt update && apt install -y curl
        curl -sfL 'https://raw.GitHubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
        orca-cli -p "${PROJECT_KEY}" image scan ${IMAGE_NAME}
